name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - "v*"

# Cancel in-progress CI jobs if there is a new push
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.check.outputs.has-changes }}
    steps:
      - name: Check for changes
        id: check
        uses: jiahuei/check-changes-action@v0
        with:
          watch-dirs: "python/"

  tests:
    runs-on: ubuntu-latest
    name: tests
    needs: check_changes
    if: ${{ needs.check_changes.outputs.has-changes == 'true' }}
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Echo
        run: echo ${{needs.check_changes.outputs.has-changes}}

  tests_noop:
    runs-on: ubuntu-latest
    name: tests
    needs: check_changes
    if: ${{ needs.check_changes.outputs.has-changes == 'false' }}
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: No-op
        run: echo ${{needs.check_changes.outputs.has-changes}}

  task0:
    runs-on: ubuntu-latest
    name: task 0
    needs: tests
    steps:
      - name: Get current time
        run: date

  task1:
    runs-on: ubuntu-latest
    name: task 0
    needs: task0
    steps:
      - name: Fail
        run: exit 1
