name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - "v*"

# Cancel in-progress CI jobs if there is a new push
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.check-changes.outputs.has-changes }}
    steps:
      - name: Check for changes
        id: check-changes
        uses: jiahuei/check-changes-action@v0
        with:
          watch-dir: "src/emu"

  tests:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.has-changes == 'true'

    steps:
      - name: Echo
        run: echo "Changes detected"
