name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - "v*"

# Cancel in-progress CI jobs if there is a new push
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.filter.outputs.has_changes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        id: filter
        shell: bash
        run: |
          WATCH_DIR='src/emu/'
          DEFAULT_BRANCH='main'

          all_changes=$(git diff --name-only ${DEFAULT_BRANCH}...HEAD)

          printf '%s\n' "--------- ALL CHANGES ---------"
          printf '%s\n' $all_changes
          printf '%s\n' "-------------------------------"

          changes=$(echo "$all_changes" | grep "^${WATCH_DIR}")
          if [ -n "$changes" ]; then
          echo "Changes detected in ${WATCH_DIR} directory."
          echo "has_changes=true" >> $GITHUB_OUTPUT
          else
          echo "No changes in ${WATCH_DIR} directory."
          echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  tests:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.has_changes == 'true'

    steps:
      - name: Echo
        run: echo "Changes detected"
